
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID NUMcalculator : commands\n\n    commands : commands command\n             |\n\n    command : '?' IDcommand : '!' expcommand : ID '=' expcommand : '!' '!'command : '$' IDexp : exp '+' termexp : exp '-' termexp : termterm : term '*' factorterm : term '/' factorfactor : IDterm : factorfactor : NUMfactor : '(' exp ')'"
    
_lr_action_items = {'?':([0,2,3,8,10,11,12,13,14,15,17,18,24,25,26,27,28,],[-3,4,-2,-4,-7,-5,-11,-15,-14,-16,-8,-6,-9,-10,-12,-13,-17,]),'!':([0,2,3,6,8,10,11,12,13,14,15,17,18,24,25,26,27,28,],[-3,6,-2,10,-4,-7,-5,-11,-15,-14,-16,-8,-6,-9,-10,-12,-13,-17,]),'ID':([0,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,],[-3,5,-2,8,14,17,-4,14,-7,-5,-11,-15,-14,-16,14,-8,-6,14,14,14,14,-9,-10,-12,-13,-17,]),'$':([0,2,3,8,10,11,12,13,14,15,17,18,24,25,26,27,28,],[-3,7,-2,-4,-7,-5,-11,-15,-14,-16,-8,-6,-9,-10,-12,-13,-17,]),'$end':([0,1,2,3,8,10,11,12,13,14,15,17,18,24,25,26,27,28,],[-3,0,-1,-2,-4,-7,-5,-11,-15,-14,-16,-8,-6,-9,-10,-12,-13,-17,]),'=':([5,],[9,]),'NUM':([6,9,16,19,20,21,22,],[15,15,15,15,15,15,15,]),'(':([6,9,16,19,20,21,22,],[16,16,16,16,16,16,16,]),'+':([11,12,13,14,15,18,23,24,25,26,27,28,],[19,-11,-15,-14,-16,19,19,-9,-10,-12,-13,-17,]),'-':([11,12,13,14,15,18,23,24,25,26,27,28,],[20,-11,-15,-14,-16,20,20,-9,-10,-12,-13,-17,]),')':([12,13,14,15,23,24,25,26,27,28,],[-11,-15,-14,-16,28,-9,-10,-12,-13,-17,]),'*':([12,13,14,15,24,25,26,27,28,],[21,-15,-14,-16,21,21,-12,-13,-17,]),'/':([12,13,14,15,24,25,26,27,28,],[22,-15,-14,-16,22,22,-12,-13,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calculator':([0,],[1,]),'commands':([0,],[2,]),'command':([2,],[3,]),'exp':([6,9,16,],[11,18,23,]),'term':([6,9,16,19,20,],[12,12,12,24,25,]),'factor':([6,9,16,19,20,21,22,],[13,13,13,13,13,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calculator","S'",1,None,None,None),
  ('calculator -> commands','calculator',1,'p_calculator','calculator_yacc.py',6),
  ('commands -> commands command','commands',2,'p_commands','calculator_yacc.py',11),
  ('commands -> <empty>','commands',0,'p_commands','calculator_yacc.py',12),
  ('command -> ? ID','command',2,'p_read_command','calculator_yacc.py',17),
  ('command -> ! exp','command',2,'p_write_command','calculator_yacc.py',22),
  ('command -> ID = exp','command',3,'p_atribute_command','calculator_yacc.py',26),
  ('command -> ! !','command',2,'p_info_command','calculator_yacc.py',30),
  ('command -> $ ID','command',2,'p_declaration_command','calculator_yacc.py',34),
  ('exp -> exp + term','exp',3,'p_exp_plus','calculator_yacc.py',38),
  ('exp -> exp - term','exp',3,'p_exp_minus','calculator_yacc.py',42),
  ('exp -> term','exp',1,'p_exp_term','calculator_yacc.py',46),
  ('term -> term * factor','term',3,'p_term_mult','calculator_yacc.py',50),
  ('term -> term / factor','term',3,'p_term_div','calculator_yacc.py',54),
  ('factor -> ID','factor',1,'p_factor_id','calculator_yacc.py',62),
  ('term -> factor','term',1,'p_term','calculator_yacc.py',69),
  ('factor -> NUM','factor',1,'p_factor_num','calculator_yacc.py',73),
  ('factor -> ( exp )','factor',3,'p_factor_exp','calculator_yacc.py',77),
]
